### ISSUE TITLE
re:tiny cad in contrib

### ISSUE THREAD

**Issue by meta-androcto** [zeffii/mesh_tiny_cad#44]
hi, given 2.78 may well be the last of the series & addons will most likely break permanently in 2.8,
I'm looking at putting the best, most popular addons into Blender Release.
Is this something you would contribute to? Can we move tinycad? any other's you would suggest?
thanks, drop in to blenderpython.
the night may be long, I want to have 2.78 release in best position for people to use for 12 months whilst 2.8 is being built.

**Comment by zeffii** [comment]
hi @meta-androcto ! 

Yes, by all means mesh_tinyCAD can be included -- though I would prefer that the master of _this_ repo was used instead of the current version in `scripts/addons_contrib` . This repo has a tidier `__init__` and overal structure. 

I'm even debating whether to make the `icons_two` branch default, but in lieu of sufficient testing time i'm inclined to not do that.
